name: PDF to EPS Converter

on:
  workflow_dispatch: # Biar bisa loe jalanin manual bro

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Ghostscript
        run: |
          sudo apt-get update
          sudo apt-get install -y ghostscript

      - name: Konversi PDF ke EPS
        run: |
          # Buat folder output biar kaga berantakan
          mkdir -p output
          
          # Looping file pdf di folder input
          for file in input/*.pdf; do
            if [ -f "$file" ]; then
              filename=$(basename "$file" .pdf)
              echo "Lagi proses: $file"
              
              # Pake Ghostscript buat konversi yang bersih
              gs -q -dNOPAUSE -dBATCH -sDEVICE=eps2write -sOutputFile="output/${filename}.eps" "$file"
            fi
          done

      - name: Upload Hasil Konversi
        uses: actions/upload-artifact@v4
        with:
          name: file-eps-hasil-konversi
          path: output/
