name: PDF to EPS (Inkscape LFS Mode)

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true # Wajib dinyalain biar file aslinya ditarik, bukan pointernya doang

      - name: Extract Inkscape dari LFS
        run: |
          # Kasih izin eksekusi
          chmod +x tools/inkscape.AppImage
          
          # Ekstrak isi AppImage-nya
          # Ini bakal bikin folder baru namanya 'squashfs-root'
          ./tools/inkscape.AppImage --appimage-extract > /dev/null
          
          # Bikin link biar perintah 'inkscape' bisa dipanggil langsung
          sudo ln -s $(pwd)/squashfs-root/AppRun /usr/local/bin/inkscape
          
          echo "Inkscape LFS siap digas brooohh!"

      - name: Konversi PDF ke EPS (Anti Missing Font)
        run: |
          mkdir -p output
          
          for file in input/*.pdf; do
            if [ -f "$file" ]; then
              filename=$(basename "$file" .pdf)
              echo "Giles font di file: $file"
              
              # Pake --export-text-to-path biar font Bebas Neue loe kaga lari
              inkscape "$file" \
                --export-type=eps \
                --export-text-to-path \
                --export-filename="output/${filename}.eps"
            fi
          done

      - name: Upload Hasil
        uses: actions/upload-artifact@v4
        with:
          name: file-eps-rapih-lfs
          path: output/
