name: PDF to EPS

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Extract Inkscape
        run: |
          chmod +x tools/inkscape.AppImage
          ./tools/inkscape.AppImage --appimage-extract > /dev/null
          sudo ln -s $(pwd)/squashfs-root/AppRun /usr/local/bin/inkscape

      - name: PDF ke EPS
        run: |
          mkdir -p output
          
          for file in input/*.pdf; do
            if [ -f "$file" ]; then
              filename=$(basename "$file" .pdf)
              echo "Giles font di file: $file"
              inkscape "$file" \
                --export-type=eps \
                --export-text-to-path \
                --export-filename="output/${filename}.eps"
            fi
          done

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: file-eps
          path: output/
