name: Inkscape

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download-inkscape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Preparing
        run: |
          git lfs install
          git lfs track "*.AppImage"
          git add .gitattributes
          mkdir -p tools
          rm -f tools/inkscape.AppImage 
          wget -O tools/inkscape.AppImage https://media.inkscape.org/dl/resources/file/Inkscape-091e20e-x86_64.AppImage
          FILESIZE=$(stat -c%s "tools/inkscape.AppImage")
          if [ $FILESIZE -lt 100000000 ]; then
            exit 1
          fi
          chmod +x tools/inkscape.AppImage

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git config --global http.postBuffer 524288000
          
          git add tools/inkscape.AppImage
          git commit -m "Add real portable Inkscape [skip ci]" || echo "No changes"
          git push origin main
